export const ENTITY_TYPE = "ENTITY_TYPE"
export const WEAK_ENTITY_TYPE = "WEAK_ENTITY_TYPE"
export const RELATIONSHIP_TYPE = "RELATIONSHIP_TYPE"
export const IDENTIFICATION_RELATIONSHIP_TYPE =
  "IDENTIFICATION_RELATIONSHIP_TYPE"
export const ATTRIBUTE = "ATTRIBUTE"
export const MULTIPLE_VALUE_ATTRIBUTE = "MULTIPLE_VALUE_ATTRIBUTE"
export const DERIVED_ATTRIBUTE = "DERIVED_ATTRIBUTE"

export type DiagramNodeType =
  | typeof ENTITY_TYPE
  | typeof WEAK_ENTITY_TYPE
  | typeof RELATIONSHIP_TYPE
  | typeof IDENTIFICATION_RELATIONSHIP_TYPE
  | typeof ATTRIBUTE
  | typeof MULTIPLE_VALUE_ATTRIBUTE
  | typeof DERIVED_ATTRIBUTE
